Add Netgear ReadyNAS and ReadyData appliances
prometheus/snmp_exporter pull request #895
Opened 2023-06-13 15:18 UTC by reynico

2023-08-09 04:31 UTC, SuperQ commented
This needs a rebase.

2023-08-09 04:32 UTC, SuperQ requested changes
Rebase required.

2023-11-24 12:33 UTC, SuperQ commented on generator/generator.yml
> +      - 1.3.6.1.2.1.25.3.3.1.2        # CPU status
With the refactoring of the generator, we only put device-specific walks in modules. The other walks are accounted for in other modules. For example the `hrDevice` module.


Also, let's be a little more specific in our walk specifications. Not the whole enterprise.

```suggestion
      - 1.3.6.1.4.1.4526              # Raid/Disks status
```

2023-11-24 19:36 UTC, reynico commented
up to this point, and given the divergence between branches, I think it'd better start from scratch (-: @SuperQ what do you think?

2023-11-24 19:42 UTC, closed without merging